name: summiting_analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - mat73=0.62.0
  - scipy=1.11.1
  - numpy=1.24.3
  - hdf5storage=0.1.19
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - numba=0.57.1